### ISSUE TITLE
Missing traits for DSL

### ISSUE THREAD

**Issue by nathan-K-** [jenkinsci/bitbucket-branch-source-plugin#271] opened 2020-01-15 14:33 UTC
Hi !

- [x] Jenkins version 2.176.1
- [x] Plugin version 2.4.4
- [x] Bitbucket server version 5.16.0

### Description

It's working fine when create through "New Item / Bitbucket Team/Porject".
Trying to configure the plugin to be generated via DSL, there is some complications.

Some important traits are missing from the doc `/plugin/job-dsl/api-viewer/index.html#path/organizationFolder-organizations-bitbucket`, like **branchDiscoveryTrait**, without whom the plugin isn't listing any branch.
Some other traits are also missing, eg **Discover pull requests from origin**, or **Discover pull requests from forks**.

Do you have any information on that ?

Cheers,

**Comment by casz** [comment] 2020-01-15 14:41
duplicate of #258

**Closed by casz** 2020-01-15 14:41 UTC

**Comment by nathan-K-** [comment] 2020-01-17 19:36
Hi,

Even they both are about traits, I'm actually seeing the "Traits" dropdown (that seems to be the issue in #258), but some traits (like branchDiscoveryTrait) are missing in it...
