### ISSUE TITLE
Provide option to retrigger a failed build.

### ISSUE THREAD

**Issue by mkjkec2005** [jenkinsci/bitbucket-branch-source-plugin#828] opened 2024-03-23 02:46 UTC
### What feature do you want to see added?

Currently the plugin does not provide an option to retrigger failed builds. Users need to go to Jenkins and run the failed PR build job. Is there a way to achieve this from Bitbucket?

**Comment by mkjkec2005** [comment] 2024-03-27 03:46
Gentle reminder. Could you please help? Or please suggest if there is an alternative.

**Comment by mkjkec2005** [comment] 2024-03-27 11:27
Thank you @KalleOlaviNiemitalo. The problem with comment is how do we ensure that we post using a rebuild link? Jenkins rebuild will needs a crumb for form submission or post request.

**Comment by nfalco79** [comment] 2024-11-18 00:31
Replay failed build is not so trivial, because depending of which is the cause of the failure (compile / test erro) could trigger an infinite build loop because the specific commit will always fail. This mean start to tricks and specialized logic of when replay a build that is not the goal of this plugin.
This plugin (like github-branch-source-plugin and gitlab-branch-source-plugin) is an implementation of branch-api-plugin to configure how to checkout sources and which branches should be configured as a job.
Here you can find implementations of the branch-api interfaces and trait implementations. Build strategies, branch properties are developed in other plugins. This is the reason why I'm closing this request as "Won't do" (JIRA resolution)

**Closed by nfalco79** 2024-11-18 00:31 UTC
Labels: enhancement
