### ISSUE TITLE
Retry on SSL error

### ISSUE THREAD

**Issue by JonatanPlesko** [jenkinsci/bitbucket-branch-source-plugin#471] opened 2021-08-13 12:10 UTC
Hi, I'm very frequently experiencing the following error with the build failing within <100ms:
```
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at java.base/sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:526)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:504)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:437)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:859)
Caused: java.io.IOException: Communication error for url: /rest/api/1.0/projects/Sample/repos/sample-project/branches?start=0&limit=200
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:889)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getResources(BitbucketServerAPIClient.java:835)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getServerBranches(BitbucketServerAPIClient.java:588)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getBranches(BitbucketServerAPIClient.java:579)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:795)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:100)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:100)
	at hudson.model.Executor.run(Executor.java:433)
Finished: FAILURE
```

### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.306
OS: Mac OS X - 10.16
---
jsch:0.1.55.2
ws-cleanup:0.39
blueocean-commons:1.24.8
mercurial:2.15
echarts-api:5.1.2-6
structs:1.23
sse-gateway:1.24
conditional-buildstep:1.4.1
apache-httpcomponents-client-4-api:4.5.13-1.0
parameterized-trigger:2.41
bootstrap5-api:5.1.0-1
sshd:3.1.0
pipeline-model-extensions:1.9.1
build-with-parameters:1.5.1
workflow-aggregator:2.6
mailer:1.34
git:4.8.1
handy-uri-templates-2-api:2.1.8-1.0
theme-manager:0.6
bootstrap4-api:4.6.0-3
jquery3-api:3.6.0-2
delivery-pipeline-plugin:1.4.2
command-launcher:1.6
dark-theme:0.0.12
workflow-api:2.46
docker-build-publish:1.3.3
extended-choice-parameter:0.82
workflow-job:2.41
ssh-credentials:1.19
authentication-tokens:1.4
blueocean-rest-impl:1.24.8
github-branch-source:2.11.2
htmlpublisher:1.25
javadoc:1.6
workflow-cps-global-lib:2.21
blueocean-web:1.24.8
jackson2-api:2.12.4
disable-failed-job:1.15
ssh-slaves:1.32.0
docker-workflow:1.26
pipeline-stage-tags-metadata:1.9.1
blueocean-pipeline-scm-api:1.24.8
pipeline-milestone-step:1.3.2
credentials:2.5
docker-java-api:3.1.5.2
cloudbees-bitbucket-branch-source:2.9.10
jquery:1.12.4-1
github:1.33.1
lockable-resources:2.11
jquery-detached:1.2.1
bitbucket:1.1.29
blueocean-personalization:1.24.8
workflow-scm-step:2.13
matrix-auth:2.6.8
matrix-project:1.19
pipeline-stage-step:2.5
pipeline-build-step:2.15
antisamy-markup-formatter:2.1
pipeline-input-step:2.12
bouncycastle-api:2.21
checks-api:1.7.2
handlebars:3.0.8
blueocean:1.24.8
variant:1.4
momentjs:1.1.1
blueocean-jwt:1.24.8
plain-credentials:1.7
docker-commons:1.17
aws-java-sdk:1.11.995
docker-plugin:1.2.2
jobConfigHistory:2.28.1
copyartifact:1.46.1
git-client:3.9.0
timestamper:1.13
gradle:1.37.1
pipeline-rest-api:2.19
workflow-basic-steps:2.23
github-api:1.123
blueocean-i18n:1.24.8
ldap:2.7
blueocean-events:1.24.8
jaxb:2.3.0.1
blueocean-core-js:1.24.8
maven-plugin:3.12
aws-credentials:1.29
thinBackup:1.10
blueocean-config:1.24.8
blueocean-github-pipeline:1.24.8
font-awesome-api:5.15.3-4
credentials-binding:1.27
pipeline-model-definition:1.9.1
config-file-provider:3.8.1
pipeline-stage-view:2.19
sonar:2.13.1
token-macro:266.v44a80cf277fd
slack:2.48
blueocean-display-url:2.4.1
workflow-multibranch:2.26
script-security:1.78
git-server:1.10
snakeyaml-api:1.29.1
docker-build-step:2.8
discard-old-build:1.05
ssh-agent:1.23
workflow-step-api:2.24
run-condition:1.5
rebuild:1.32
okhttp-api:3.14.9
pipeline-graph-analysis:1.11
blueocean-git-pipeline:1.24.8
popper2-api:2.9.3-1
pipeline-model-api:1.9.1
plugin-util-api:2.4.0
jenkins-design-language:1.24.8
windows-slaves:1.8
workflow-cps:2.93
popper-api:1.16.1-2
blueocean-autofavorite:1.2.4
workflow-durable-task-step:2.39
trilead-api:1.0.13
branch-api:2.6.5
jdk-tool:1.5
whitesource:21.1.2
cloudbees-folder:6.16
blueocean-pipeline-editor:1.24.8
Parameterized-Remote-Trigger:3.1.5.1
blueocean-dashboard:1.24.8
jjwt-api:0.11.2-9.c8b45b8bb173
durable-task:1.38
kpp-management-plugin:1.0.0
junit:1.51
pam-auth:1.6
pubsub-light:1.16
next-build-number:1.6
caffeine-api:2.9.1-23.v51c4e2c879c8
scm-api:2.6.5
blueocean-pipeline-api-impl:1.24.8
ace-editor:1.1
display-url-api:2.3.5
workflow-support:3.8
resource-disposer:0.16
blueocean-rest:1.24.8
build-timeout:1.20
favorite:2.3.3
versionnumber:1.9
blueocean-bitbucket-pipeline:1.24.8
mapdb-api:1.0.9.0
git-parameter:0.9.13
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
The above report should be sufficient, I'm only using this one device (Mac Mini with M1 processor).
```

### Reproduction steps

I have my Jenkins instance behind a firewall and am using the Bitbucket Server. The setup was done as described in this article:
https://www.jenkins.io/blog/2019/01/07/webhook-firewalls/

Running manual builds **never fails**. However, when the hook event comes, the build often fails within <100ms with the above error message. I believe some kind of retry mechanism would help, but I'm also open to other ideas if you think the issue might be on my side.

### Results

Expected result:

A proper workflow should be triggered. If an SSL exception comes, maybe some kind of a retry mechanism instead of an instant failure.

Actual result:

In about 50% of the cases, the build instantly fails with the "peer not authenticated" message.

**Comment by mderaspe** [comment] 2023-01-04 16:46
Is there any progress on this issue so far ? We've been experiencing this for a long time... it's hard to build a reliable CD pipeline if you get 50% failure on bitbucket / jenkins communications.

**Comment by jeff1326** [comment] 2023-01-13 19:31
Does someone know a workaround ? This drives me nuts...

![image](https://user-images.githubusercontent.com/12941529/212402811-fb6f6011-1317-4dbe-8e83-a52c2383e039.png)

**Comment by aldehoff** [comment] 2023-01-16 08:13
This is also a problem at our site! We're running Jenkins 2.386 (latest) with version 791.vb_eea_a_476405b (latest) of this plugin to integrate with a Bitbucket Cloud workspace. The Jenkins server is behind a corporate firewall, hence we use branch indexing instead of webhooks. Builds triggered automatically by branch indexing, cron jobs, as well as the build status notifications frequently fail due to TLS errors within the first second of establishing contact with api.bitbucket.org. The problem is very well described by the original poster, we see the exact same messages. The setup used to work fine for years, but build success rate has declined dramatically during the last two months. Firewall rules and deep package inspection have been disabled by corporate IT, we've updated Jenkins and all plugins (previously 2.366 for the server and 2.7.9 for the plugin), and we're in contact with Bitbucket support to exclude authentication issues or outages on their side. All to no avail! Is there anyone here who can comment on this and suggest ways to troubleshoot or mitigate this? Otherwise we're likely forced to ditch Jenkins and this plugin for good and look elsewhere for a more functional build server.

**Comment by aldehoff** [comment] 2023-01-18 08:40
After a lot of back and forth with our local IT support as well as Bitbucket support we have finally seen an improvement by updating the JDK version from 11.0.1 to 17.0.2. A lot of things were tried, including OS updates, server updates, plugin updates, changes to the firewall and deep package inspection "security" tools deployed by IT, etc. None of it made a difference, but the JDK update seems to have done it. I'm equally thrilled and surprised by this, and I hope that this hint helps others here who can maybe confirm that this is the root cause.

**Comment by aldehoff** [comment] 2023-01-18 09:01
@KalleOlaviNiemitalo our local Jenkins only. JDK 17 is the latest version supported by Jenkins 2.386. We integrate with Bitbucket Cloud, so no control over the server side.

**Comment by kmurray2bee** [comment] 2023-07-15 07:20
I wonder if this could have been related to this JDK bug https://bugs.openjdk.org/browse/JDK-8212885

**Comment by nfalco79** [comment] 2024-11-03 01:58
I'm closing this issue becuase seems the bug is related on how the JDK handle SSL connection. Updating to latest JDK 17 should resolve.
If persist than reopen as suggestion to implement a connection retry

**Closed by nfalco79** 2024-11-03 01:58 UTC
Labels: bug
